name: Salesforce Code Analyzer 

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - dev
      - uat
  workflow_dispatch:

jobs:
  analyzetest:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v4  

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH  # Ensure CLI is in PATH

      - name: Verify Salesforce CLI Installation
        run: sf --version

      - name: Debug plugins
        run: sf plugins
      - name: Run CA
        run: |
          sf scanner run -t "./force-app/" -o "resultsPMD.csv" -f csv --engine pmd:all
          sf scanner run -t "./force-app/" -o "resultsCPD.csv" -f csv --engine cpd
          
          # set +e
          # sf code-analyzer run --rule-selector pmd:all -w "force-app" --output-file results.csv -t 3
          # EXIT_CODE_1=$?
          # sf code-analyzer run --rule-selector cpd -w "force-app" --output-file resultsCPD.csv -t 3
          # EXIT_CODE_2=$?
          # sf code-analyzer run --rule-selector flowtest -w "force-app" --output-file resultsFlowtest.csv -t 3
          # EXIT_CODE_3=$?
    
          # # If any command failed, exit with a non-zero status
          # if [ $EXIT_CODE_1 -ne 0 ] || [ $EXIT_CODE_2 -ne 0 ] || [ $EXIT_CODE_3 -ne 0 ]; then
          #   exit 1
          # fi

          

      - name: ANALYZER RESULTS!!! Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: |
            results.csv
            resultsCPD.csv
            resultsFlowtest.csv


      
