name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Checkout Code  
      uses: actions/checkout@v4  
    - name: Checkout java
      run: java -version

    - name: Set up latest Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: Checkout Python  
      run: python --version 
    - name: test install java
      uses: actions/setup-java@v4
      with:
          distribution: 'oracle'
          java-version: '21'
          check-latest: true
    - run: java -version
    - name: Checkout java 2
      run: java -version
      
